version: 2.1

executors:
  linux:
    machine:
      image: python:3.8

jobs:
  AA:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: A
          command: |
            nproc


    parallelism: 1
workflows:
  AA:
    jobs:
      - AA:
          matrix:
            parameters:
              os: [linux]
