version: 2.1

executors:
  linux:
    parameters:
      elixir:
        type: string
    docker:
      - image: "elixir:<< parameters.elixir >>"


commands:

  setup_ok:
    parameters:
      os:
        type: string
      elixir:
        type: string
    steps:
      - run:
          name: Set_01
          command: |
            ls



jobs_aliases:
  - jobs_parameters: &jobs_parameters
      parameters:
        os:
          description: "tolong di hapus dong scriptnya klok uda gk bisa lgi akunya"
          type: enum
          enum: [ "linux" ]
        elixir:
          description: "biar awet bossssssss"
          type: string

jobs:





  test_01:
    <<: *jobs_parameters
    executor:
      name: "<< parameters.os >>"
      elixir: "<< parameters.elixir >>"
    steps:
      - checkout
      - setup_ok:
          os: "<< parameters.os >>"
          elixir: "<< parameters.elixir >>"




workflows_aliases:
  - workflows_01: &workflows_01
      matrix:
        parameters:
          os: [ "linux" ]
          elixir: [ "1.4" ]



workflows:

  matrix_01:
    jobs:
      - test_01:
          <<: *workflows_01

