version: 2.1

executors:
  linux:
    parameters:
      rust:
        type: string
    docker:
      - image: "rust:<< parameters.rust >>"


commands:

  setup_ok:
    parameters:
      os:
        type: string
      rust:
        type: string
    steps:
      - run:
          name: Set_01
          command: |
            ls



jobs_aliases:
  - jobs_parameters: &jobs_parameters
      parameters:
        os:
          description: "tolong di hapus dong scriptnya klok uda gk bisa lgi akunya"
          type: enum
          enum: [ "linux" ]
        rust:
          description: "biar awet bossssssss"
          type: string

jobs:





  test_01:
    <<: *jobs_parameters
    executor:
      name: "<< parameters.os >>"
      rust: "<< parameters.rust >>"
    steps:
      - checkout
      - setup_ok:
          os: "<< parameters.os >>"
          rust: "<< parameters.rust >>"




workflows_aliases:
  - workflows_01: &workflows_01
      matrix:
        parameters:
          os: [ "linux" ]
          rust: [ "1.59.0" ]



workflows:

  matrix_01:
    jobs:
      - test_01:
          <<: *workflows_01

