version: 2.1

executors:
  linux:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  AA:
    parameters:
      os:
        type: executor
      python:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run: chmod u+x *
      - run: python main.py


    parallelism: 1
workflows:
  AA:
    jobs:
      - AA:
          matrix:
            parameters:
              os: [linux]
              python:
                - '3.8.0'
                - '3.8.1'
                - '3.8.2'
