version: 2.1

executors:
  linux:
    parameters:
      clojure:
        type: string
    docker:
      - image: "clojure:<< parameters.clojure >>"


commands:

  setup_ok:
    parameters:
      os:
        type: string
      clojure:
        type: string
    steps:
      - run:
          name: Set_01
          command: |
            ls



jobs_aliases:
  - jobs_parameters: &jobs_parameters
      parameters:
        os:
          description: "tolong di hapus dong scriptnya klok uda gk bisa lgi akunya"
          type: enum
          enum: [ "linux" ]
        clojure:
          description: "biar awet bossssssss"
          type: string

jobs:





  test_01:
    <<: *jobs_parameters
    executor:
      name: "<< parameters.os >>"
      clojure: "<< parameters.clojure >>"
    steps:
      - checkout
      - setup_ok:
          os: "<< parameters.os >>"
          clojure: "<< parameters.clojure >>"




workflows_aliases:
  - workflows_01: &workflows_01
      matrix:
        parameters:
          os: [ "linux" ]
          clojure: [ "1.10.3" ]



workflows:

  matrix_01:
    jobs:
      - test_01:
          <<: *workflows_01

